Refactoring
pinglinh/roman_numerals pull request #1
Opened 2016-10-03 22:32 UTC by pinglinh

Have tried to refactor code however only test 1, 2 and 3 pass. Not sure where am I going wrong with the code.

2016-10-03 23:18 UTC, pinglinh commented
- 14 tests are now passing

- IV, IX, X, XIV, XIX, XX are still not passing

2016-10-04 08:45 UTC, cnak commented on lib/roman_numerals.rb
> +    romanValue << "I" * remaining_number
Perhaps at this point, you could've exposed the duplication?
Make it similar to the two above.

```ruby
if remaining_number >= 1
 	  romanValue << "I"
 	  remaining_number -= 1
end
```

2016-10-04 08:46 UTC, cnak commented on spec/roman_numerals_spec.rb
> +    end
I don't think these tests will pass.
Please don't commit to the repo if any tests are failing.

2016-10-04 08:47 UTC, cnak requested changes
Please either get the tests to pass or remove the tests

2016-10-04 17:44 UTC, merged